const listItems = [
    "Ace Hotel",
    "ARMEDANGELS",
    "BERLIN DESIGN WEEK",
    "Berliner Berg",
    "BITE CLUB",
    "Budweiser Budvar",
    "ChungKing Noodles",
    "Designpreis Brandenburg",
    "Die Techniker",
    "European Street Food Awards",
    "Grundmann Dentistry",
    "HORNBACH Werkstück",
    "HORNBACH macht Schule",
    "iF Design",
    "Kopka",
    "KLH Maßschuhe",
    "Lode & Stijn",
    "Luya",
    "MEISSEN",
    "Motel Beer & Coffee",
    "PAPER & TEA",
    "rocket & basil",
    "Seeberger Gruppe",
    "Shiori",
    "SPOC Magazin",
    "stocubo",
    "STUR",
    "World of Coffee",
    "yamo",
  ];

  export default listItems